os: Visual Studio 2015

# version format
version: 3.0.0.{build}

cache:
  - packages -> **\packages.config              # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

branches:
  only:
    - v2
    - v2-release
    - v3
    - v3-release

# UMBRACO_PACKAGE_PRERELEASE_SUFFIX if a rtm release build this should be blank, otherwise if empty will default to alpha
# example UMBRACO_PACKAGE_PRERELEASE_SUFFIX=beta
init:
  - set UMBRACO_PACKAGE_PRERELEASE_SUFFIX=

build_script:
  - cd BuildPackage
  - Build.bat

artifacts:
  - path: BuildPackage\artifacts\*.nupkg
  - path: BuildPackage\artifacts\*.zip

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/umbraco-core-property-value-converters/
    api_key:
      secure: SASQGWG/4zNns7bwSSsJ5RPvKcKfJsBeEPuw69wsVPA3PO739QmzVtc5VwQwgvbr
    artifact: /.*\.nupkg/
    on:
      branch: v2

  - provider: NuGet
    server: https://www.myget.org/F/umbraco-core-property-value-converters/
    api_key:
      secure: SASQGWG/4zNns7bwSSsJ5RPvKcKfJsBeEPuw69wsVPA3PO739QmzVtc5VwQwgvbr
    artifact: /.*\.nupkg/
    on:
      branch: v2-release

  - provider: NuGet
    server: 
    api_key:
      secure: adk3pI9HCByZg2VRxplX9UR6qHf97bA3as6dusxLswCKI8BQQE8DO5a0frLrI+EO
    artifact: /.*\.nupkg/
    on:
      branch: v2-release

  - provider: NuGet
    server: https://www.myget.org/F/umbraco-core-property-value-converters/
    symbol_server: https://nuget.symbolsource.org/MyGet/umbraco-core-property-value-converters
    api_key:
      secure: SASQGWG/4zNns7bwSSsJ5RPvKcKfJsBeEPuw69wsVPA3PO739QmzVtc5VwQwgvbr
    artifact: /.*\.nupkg/
    on:
      branch: v3

    # Umbraco MyGet community feed
  - provider: NuGet
    server: https://www.myget.org/F/umbraco-packages/api/v2/package
    symbol_server: https://nuget.symbolsource.org/MyGet/umbraco-packages
    api_key:
      secure: SASQGWG/4zNns7bwSSsJ5RPvKcKfJsBeEPuw69wsVPA3PO739QmzVtc5VwQwgvbr
    artifact: /.*\.nupkg/
    on:
      branch: v3

  - provider: NuGet
    server: https://www.myget.org/F/umbraco-core-property-value-converters/
    symbol_server: https://nuget.symbolsource.org/MyGet/umbraco-core-property-value-converters
    api_key:
      secure: SASQGWG/4zNns7bwSSsJ5RPvKcKfJsBeEPuw69wsVPA3PO739QmzVtc5VwQwgvbr
    artifact: /.*\.nupkg/
    on:
      branch: v3-release
      appveyor_repo_tag: true        # deploy on tag push only

  - provider: NuGet
    server: 
    api_key:
      secure: adk3pI9HCByZg2VRxplX9UR6qHf97bA3as6dusxLswCKI8BQQE8DO5a0frLrI+EO
    artifact: /.*\.nupkg/
    on:
      branch: v3-release
      appveyor_repo_tag: true        # deploy on tag push only

  # GitHub Deployment for releases
#  - provider: GitHub
#    auth_token:
#      secure: c0LwOGqoFZIieyy8CHrUtYQOD0HL0rG5tV2DS+8FHv34BKs/LSGGtmWWep5O7GbV
#    artifact: /.*\.zip/            # upload all Zip packages to release assets
#    draft: false
#    prerelease: false
#    on:
#      branch: v3-release
#      appveyor_repo_tag: true        # deploy on tag push only